### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by BigBlueHat** [azaroth42/MangoServer#1]
It's a bit hard for people to find this on GitHub and know (from search) that it's annotation related. Worth a change?

**Comment by azaroth42** [comment]
Not sure that a different name would make it much easier to find :)
But ... suggestions?

**Comment by BigBlueHat** [comment]
Completely your call. I was thinking something like: `web-annotation-protocol-with-mongo-and-javascript` :stuck_out_tongue_winking_eye:

**Comment by azaroth42** [comment]
MangoServer doesn't have many collisions. I'll write better documentation to make it easier to find. It's not supposed to be production quality, just a reference implementation :)
